version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ğŸ¦ˆ"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "ğŸ³"

  - package-ecosystem: "docker"
    directory: "/docker/gtsam"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "ğŸ³"

  - package-ecosystem: "pip"
    directory: "/media/plots"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "ğŸ™"

  - package-ecosystem: "pip"
    directory: "/media/diagrams"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "ğŸ™"
