version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "ğŸ¦ˆ"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "ğŸ³"

  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "ğŸ™"

  - package-ecosystem: "devcontainers"
    directory: "/.devcontainer/gpu"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "ğŸ™"
