repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: ^docker/tmuxp/intro/tips\.txt$
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: ['--maxkb=10000']

  - repo: https://github.com/psf/black
    rev: 26.1.0
    hooks:
      - id: black

  - repo: https://github.com/snelsondurrant/coug-hooks
    rev: 38b761a58f17a436b0e00792eb33485e51e43e61
    hooks:
      - id: ament_uncrustify
        files: ^packages/.*\.(h\+\+|h|hh|hxx|hpp|cuh|c|cc|cpp|cxx|cu)$
      - id: ament_cpplint
        files: ^packages/.*\.(h\+\+|h|hh|hxx|hpp|cuh|c|cc|cpp|cxx|cu)$
      # - id: ament_cppcheck
      #   files: ^packages/.*\.(h\+\+|h|hh|hxx|hpp|cuh|c|cc|cpp|cxx|cu)$
      - id: ament_flake8
        files: ^packages/.*\.py$
      - id: ament_pep257
        files: ^packages/.*\.py$
      - id: ament_lint_cmake
      - id: ament_xmllint
        files: ^packages/.*\.xml$
      - id: ament_copyright
        files: ^packages/
