repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: ^tmuxp/intro/tips\.txt$
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: ['--maxkb=10000']

  - repo: https://github.com/psf/black
    rev: 26.1.0
    hooks:
      - id: black

  - repo: https://github.com/cougars-auv/coug-hooks
    rev: v1.0.0
    hooks:
      - id: ament_uncrustify
        files: ^ros2_ws/src/.*\.(h\+\+|h|hh|hxx|hpp|cuh|c|cc|cpp|cxx|cu)$
      - id: ament_cpplint
        files: ^ros2_ws/src/.*\.(h\+\+|h|hh|hxx|hpp|cuh|c|cc|cpp|cxx|cu)$
      # - id: ament_cppcheck
      #   files: ^ros2_ws/src/.*\.(h\+\+|h|hh|hxx|hpp|cuh|c|cc|cpp|cxx|cu)$
      - id: ament_flake8
        files: ^ros2_ws/src/.*\.py$
      - id: ament_pep257
        files: ^ros2_ws/src/.*\.py$
      - id: ament_lint_cmake
      - id: ament_xmllint
        files: ^ros2_ws/src/.*\.xml$
      - id: ament_copyright
        files: ^ros2_ws/src/
