/**:
  ekf_filter_node_odom:
    ros__parameters:
      frequency: 30.0
      two_d_mode: false
      publish_tf: false # Published by IEKF instead
      print_diagnostics: true

      twist0: dvl/twist
      twist0_config: [false, false, false, # X, Y, Z
                      false, false, false, # Roll, Pitch, Yaw
                      true,  true,  true,  # Vx, Vy, Vz
                      false, false, false, # Vroll, Vpitch, Vyaw
                      false, false, false] # Ax, Ay, Az
      twist0_queue_size: 5

      imu0: imu/data
      imu0_config: [false, false, false, # X, Y, Z
                    false, false, false, # Roll, Pitch, Yaw
                    false, false, false, # Vx, Vy, Vz
                    true,  true,  true,  # Vroll, Vpitch, Vyaw
                    true,  true,  true]  # Ax, Ay, Az
      imu0_differential: false
      imu0_relative: true
      imu0_queue_size: 10
      imu0_remove_gravitational_acceleration: true

      use_control: false

  ekf_filter_node_map:
    ros__parameters:
      frequency: 20.0
      two_d_mode: false
      publish_tf: false # Published by FGO instead
      print_diagnostics: true

      odom0: odometry/local_ekf
      odom0_config: [false, false, false, # X, Y, Z
                     false, false, false, # Roll, Pitch, Yaw
                     true,  true,  true,  # Vx, Vy, Vz
                     true,  true,  true,  # Vroll, Vpitch, Vyaw
                     false, false, false] # Ax, Ay, Az
      odom0_queue_size: 10
      odom0_differential: false
      odom0_relative: false

      odom1: odometry/depth
      odom1_config: [false, false, true,  # X, Y, Z
                     false, false, false, # Roll, Pitch, Yaw
                     false, false, false, # Vx, Vy, Vz
                     false, false, false, # Vroll, Vpitch, Vyaw
                     false, false, false] # Ax, Ay, Az
      odom1_queue_size: 2
      odom1_differential: false
      odom1_relative: false # Absolute depth in the map frame.

      # odom2: odometry/gps
      # odom2_config: [true,  true,  false, # X, Y, Z
      #                false, false, false, # Roll, Pitch, Yaw
      #                false, false, false, # Vx, Vy, Vz
      #                false, false, false, # Vroll, Vpitch, Vyaw
      #                false, false, false] # Ax, Ay, Az
      # odom2_queue_size: 2
      # odom2_differential: false
      # odom2_relative: false # Absolute GPS position in the map frame.

      imu0: imu/ahrs
      imu0_config: [false, false, false, # X, Y, Z
                    false, false, true,  # Roll, Pitch, Yaw
                    false, false, false, # Vx, Vy, Vz
                    false, false, false, # Vroll, Vpitch, Vyaw
                    false, false, false] # Ax, Ay, Az
      imu0_queue_size: 2
      imu0_differential: false
      imu0_relative: false # Absolute heading in the map frame.

  ukf_filter_node_map:
    ros__parameters:
      frequency: 20.0
      two_d_mode: false
      publish_tf: false # Published by FGO instead
      print_diagnostics: true

      odom0: odometry/local_ekf
      odom0_config: [false, false, false, # X, Y, Z
                     false, false, false, # Roll, Pitch, Yaw
                     true,  true,  true,  # Vx, Vy, Vz
                     true,  true,  true,  # Vroll, Vpitch, Vyaw
                     false, false, false] # Ax, Ay, Az
      odom0_queue_size: 10
      odom0_differential: false
      odom0_relative: false

      odom1: odometry/depth
      odom1_config: [false, false, true,  # X, Y, Z
                     false, false, false, # Roll, Pitch, Yaw
                     false, false, false, # Vx, Vy, Vz
                     false, false, false, # Vroll, Vpitch, Vyaw
                     false, false, false] # Ax, Ay, Az
      odom1_queue_size: 2
      odom1_differential: false
      odom1_relative: false # Absolute depth in the map frame.

      # odom2: odometry/gps
      # odom2_config: [true,  true,  false, # X, Y, Z
      #                false, false, false, # Roll, Pitch, Yaw
      #                false, false, false, # Vx, Vy, Vz
      #                false, false, false, # Vroll, Vpitch, Vyaw
      #                false, false, false] # Ax, Ay, Az
      # odom2_queue_size: 2
      # odom2_differential: false
      # odom2_relative: false # Absolute GPS position in the map frame.

      imu0: imu/ahrs
      imu0_config: [false, false, false, # X, Y, Z
                    false, false, true,  # Roll, Pitch, Yaw
                    false, false, false, # Vx, Vy, Vz
                    false, false, false, # Vroll, Vpitch, Vyaw
                    false, false, false] # Ax, Ay, Az
      imu0_queue_size: 2
      imu0_differential: false
      imu0_relative: false # Absolute heading in the map frame.

/auv1/ekf_filter_node_map:
  ros__parameters:
    initial_state: [0.0, 20.0, 0.0,
                    0.0, 0.0, 0.0,
                    0.0, 0.0, 0.0,
                    0.0, 0.0, 0.0,
                    0.0, 0.0, 0.0]

/auv2/ekf_filter_node_map:
  ros__parameters:
    initial_state: [0.0, 40.0, 0.0,
                    0.0, 0.0, 0.0,
                    0.0, 0.0, 0.0,
                    0.0, 0.0, 0.0,
                    0.0, 0.0, 0.0]

/auv1/ukf_filter_node_map:
  ros__parameters:
    initial_state: [0.0, 20.0, 0.0,
                    0.0, 0.0, 0.0,
                    0.0, 0.0, 0.0,
                    0.0, 0.0, 0.0,
                    0.0, 0.0, 0.0]

/auv2/ukf_filter_node_map:
  ros__parameters:
    initial_state: [0.0, 40.0, 0.0,
                    0.0, 0.0, 0.0,
                    0.0, 0.0, 0.0,
                    0.0, 0.0, 0.0,
                    0.0, 0.0, 0.0]

/bluerov2/ekf_filter_node_map:
  ros__parameters:
    imu0: imu/data

/bluerov2/ukf_filter_node_map:
  ros__parameters:
    imu0: imu/data
