# Copyright (c) 2026 BYU FROST Lab
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

services:
  gtsam:
    image: snelsondurrant/cougars:gtsam
    build:
      context: ..
      dockerfile: docker/Dockerfile.gtsam
    profiles: [ "build-reqs" ]

  base:
    image: snelsondurrant/cougars:base
    build:
      context: ..
      dockerfile: docker/Dockerfile.base
    profiles: [ "build-reqs" ]

  mapproxy:
    image: danielsnider/mapproxy
    container_name: mapproxy-ct
    network_mode: host
    volumes:
      - ../.mapproxy:/mapproxy
    restart: unless-stopped

  dev:
    image: snelsondurrant/cougars:dev
    # build:
    #   context: ..
    #   dockerfile: docker/Dockerfile.dev
    container_name: cougars-ct
    network_mode: host
    ipc: host
    pid: host
    privileged: true
    environment:
      - DISPLAY=${DISPLAY:-:0}
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    volumes:
      - ros2-workspace:/home/frostlab-docker/ros2_ws
      - ..:/home/frostlab-docker/cougars-dev:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/localtime:/etc/localtime:ro
      - /run/udev:/run/udev:ro
      - /dev:/dev
    stdin_open: true
    tty: true
    restart: unless-stopped

volumes:
  ros2-workspace:
