/**:
  imu_converter_node:
    ros__parameters:
      input_topic: "IMUSensor"
      output_topic: "imu/data_raw"

      accel_noise_sigma: 0.0078 # [m/s^2] Accelerometer measurement noise sigmas.
      gyro_noise_sigma: 0.0012 # [rad/s] Gyroscope measurement noise sigmas.

  gps_converter_node:
    ros__parameters:
      input_topic: "GPSSensor"
      output_topic: "gps/fix"

      origin_latitude: 40.33940 # 40.23890
      origin_longitude: -111.90721 # -111.74212
      origin_altitude: 1412.0

      position_noise_sigma: 0.015 # [m] GPS position uncertainty sigmas.
      altitude_noise_sigma: 0.025 # [m] GPS altitude uncertainty sigmas.

  depth_converter_node:
    ros__parameters:
      input_topic: "DepthSensor"
      output_topic: "odometry/depth"

      noise_sigma: 0.02 # [m] Depth sensor Z-position uncertainty sigma.

  ahrs_converter_node:
    ros__parameters:
      input_topic: "RotationSensor"
      output_topic: "imu/ahrs"

      yaw_noise_sigma: 0.01745 # [rad] AHRS sensor yaw uncertainty sigma.
      roll_pitch_noise_sigma: 0.00349 # [rad] AHRS sensor roll and pitch uncertainty sigmas.

  dvl_converter_node:
    ros__parameters:
      input_topic: "DVLSensorVelocity"
      output_topic: "dvl/data"

      noise_sigma: 0.02 # [m/s] DVL body-velocity uncertainty sigmas.

  truth_converter_node:
    ros__parameters:
      input_topic: "DynamicsSensorOdom"
      output_topic: "odometry/truth"

      publish_tf: false # Whether to publish the map->base_link transform

  fin_state_publisher_node:
    ros__parameters:
      input_topic: "ControlCommand"
      output_topic: "joint_states"

  cmd_vel_converter_node:
    ros__parameters:
      input_topic: "cmd_vel"
      output_topic: "/command/agent"

  hsd_converter_node:
    ros__parameters:
      heading_topic: "heading"
      speed_topic: "speed"
      depth_topic: "depth"
      output_heading_topic: "/heading"
      output_speed_topic: "/speed"
      output_depth_topic: "/depth"

  mag_converter_node:
    ros__parameters:
      input_topic: "MagnetometerSensor"
      output_topic: "imu/mag"

      noise_sigma: 0.003 # [normalized] Magnetic field uncertainty sigmas.

  wrench_converter_node:
    ros__parameters:
      agent_topic: "/command/agent"
      control_topic: "ControlCommand"
      output_topic: "cmd_wrench"
