# Copyright (c) 2026 BYU FROST Lab
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: ROS 2 CI

on:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/ros2_ci.yml"
      - "packages/**"
  pull_request:
    branches: ["main"]
    paths:
      - ".github/workflows/ros2_ci.yml"
      - "packages/**"
  repository_dispatch:
    types: [ros2_dispatch]

jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.ccache
          key: ccache-${{ matrix.runner }}-${{ github.run_id }}
          restore-keys: |
            ccache-${{ matrix.runner }}-
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - uses: ros-industrial/industrial_ci@master
        env:
          DOCKER_IMAGE: snelsondurrant/cougars:latest
          DOCKER_PULL: true
          UPSTREAM_WORKSPACE: packages/cougars.repos
          TARGET_WORKSPACE: packages
          CCACHE_DIR: ${{ github.workspace }}/.ccache
          AFTER_SETUP_UPSTREAM_WORKSPACE: |
            git config --global --add safe.directory "*"
            vcs custom --git --args submodule update --init --recursive
